### ISSUE TITLE
Användarguide för rapportverktyget

### ISSUE THREAD

**Issue by hmps** [swedish-football-network/wp-live-report#5]
För att kunna "släppa in" externa rapportörer behövs det ordentlig dokumentation av hur verktyget fungerar och ska användas.

**Comment by Lirre** [comment]
Ja, vi får utforma det under off-season. Alla guider du gjort, tex för hur föreningar skulle sprida våran "riktig fotboll" bild, har varit super. Vi kanske kan komma fram till en guide tillsammans så kan du göra layouten?

**Comment by hmps** [comment]
Ja, det låter bra. Är det många guider? Funderar på distribution och om det är flera stycken så kanske det kan vara värt att sätta upp en Wiki.
